version: "3.9"
services:
  web:
    build: .
    ports: 
      - 5000:5000
    volumes:
      - .:/flask-app
    depends_on:
      - pgdb
  pgdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
